# Generated by Django 4.2.4 on 2024-01-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipy_name', models.CharField(max_length=100)),
                ('receipy_description', models.TextField()),
                ('receipy_image', models.ImageField(upload_to='receipy')),
            ],
        ),
    ]
